#!/bin/sh
set -e

do_systemd() {
    # tedge-mapper-collectd
    systemctl disable tedge-mapper-collectd ||:
    if [ -d /run/systemd/system ]; then
        systemctl stop tedge-mapper-collectd ||:
    fi

    # collectd
    systemctl disable collectd ||:
    if [ -d /run/systemd/system ]; then
        systemctl restart collectd ||:
    fi
}

do_initd() {
    service collectd stop ||:
    service tedge-mapper-collectd stop ||:
}

if command -V systemctl >/dev/null 2>&1; then
    do_systemd
else
    do_initd
fi
