#!/bin/sh
set -e

do_systemd() {
    if [ -d /run/systemd/system ]; then
        systemctl --system daemon-reload >/dev/null ||:
    fi

    # tedge-mapper-collectd
    systemctl unmask tedge-mapper-collectd ||:
    systemctl preset tedge-mapper-collectd ||:
    systemctl enable tedge-mapper-collectd ||:
    if [ -d /run/systemd/system ]; then
        systemctl restart tedge-mapper-collectd ||:
    fi

    # collectd
    systemctl unmask collectd ||:
    systemctl preset collectd ||:
    systemctl enable collectd ||:

    if [ -d /run/systemd/system ]; then
        systemctl restart collectd ||:
    fi
}

do_initd() {
    if command -V chkconfig >/dev/null 2>&1; then
        chkconfig --add tedge-mapper-collectd ||:
        chkconfig --add collectd ||:
    fi
    service tedge-mapper-collectd restart ||:
    service collectd restart ||:
}

if command -V systemctl >/dev/null 2>&1; then
    do_systemd
else
    do_initd
fi
